In [1]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1,2,2,6])

LabelEncoder()

In [2]:
le.classes_

array([1, 2, 6])

In [5]:
le.transform([1,1,2,6])

array([0, 0, 1, 2], dtype=int64)

In [27]:
zoo[0][12] = 'TRUE'
zoo[0][16] = 'FALSE'
zoo[0]

['TRUE',
 'FALSE',
 'FALSE',
 'TRUE',
 'FALSE',
 'FALSE',
 'TRUE',
 'TRUE',
 'TRUE',
 'TRUE',
 'FALSE',
 'FALSE',
 'TRUE',
 'FALSE',
 'FALSE',
 'TRUE',
 'FALSE']

In [28]:
le.inverse_transform(zoo[0])

C:\Users\gudrb\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:518: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [11]:
le.fit(["paris","paris","tokyo","amsterdam"])

LabelEncoder()

In [12]:
list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [13]:
le.transform(["tokyo","tokyo","paris"])

array([2, 2, 1], dtype=int64)

In [41]:
import csv
with open("zoo.csv") as f:
    zoo = csv.reader(f)
    zoo = list(zoo)
zoo[0][0]='TRUE'

In [34]:
import numpy as np
zoo = np.array(zoo)
zoo.shape

(101, 17)

In [43]:
set(list(zoo[1]))

{'4', 'FALSE', 'TRUE', 'mammal'}

In [47]:
unique = []
for i in zoo:
    unique.extend(list(set(i)))
unique=list(set(unique))

In [48]:
le = preprocessing.LabelEncoder()
le.fit(unique)

LabelEncoder()

In [49]:
le.classes_

array(['0', '2', '4', '5', '6', '8', 'FALSE', 'TRUE', 'amphibian', 'bird',
       'fish', 'insect', 'invertebrate', 'mammal', 'reptile'],
      dtype='<U12')

In [55]:
print(zoo[0])
le.transform(zoo[0])


['TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', '4', 'FALSE', 'FALSE', 'TRUE', 'mammal']


array([ 7,  6,  6,  7,  6,  6,  7,  7,  7,  7,  6,  6,  2,  6,  6,  7, 13],
      dtype=int64)

In [53]:
le.transform(['mammal'])

array([13], dtype=int64)

In [58]:
le.inverse_transform(le.transform(zoo[0]))

C:\Users\gudrb\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array(['TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE',
       'TRUE', 'TRUE', 'FALSE', 'FALSE', '4', 'FALSE', 'FALSE', 'TRUE',
       'mammal'], dtype='<U12')