1-A
1)

In [54]:
import csv
with open("zoo.csv") as f:
    zoo = csv.reader(f)
    zoo = list(zoo)
zoo[0][0]='TRUE'

In [48]:
from sklearn import preprocessing
def uniq_values(list1):
    unique = []
    for i in list1:
        unique.extend(list(set(i)))
    unique=list(set(unique))
    return list(set(unique))

In [49]:
uniq_values(zoo)

['fish',
 '4',
 'FALSE',
 '8',
 '6',
 'TRUE',
 '2',
 'insect',
 'amphibian',
 '0',
 'invertebrate',
 'mammal',
 '5',
 'reptile',
 'bird']

2)

In [50]:
sym_dict = {}
unique = uniq_values(zoo)
j =0
for i in unique:
    sym_dict[i]=j
    j = j+1

In [51]:
sym_dict

{'fish': 0,
 '4': 1,
 'FALSE': 2,
 '8': 3,
 '6': 4,
 'TRUE': 5,
 '2': 6,
 'insect': 7,
 'amphibian': 8,
 '0': 9,
 'invertebrate': 10,
 'mammal': 11,
 '5': 12,
 'reptile': 13,
 'bird': 14}

3)

In [60]:
def change_symbol(list1,sym_dict):
    for i in range(len(list1)):
        for j in range(len(list1[0])):
            list1[i][j] = sym_dict[list1[i][j]]
    return list1
zoo_list = change_symbol(zoo,sym_dict)
zoo_list

[[5, 2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 1, 2, 2, 5, 11],
 [5, 2, 2, 5, 2, 2, 2, 5, 5, 5, 2, 2, 1, 5, 2, 5, 11],
 [2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 5, 9, 5, 2, 2, 0],
 [5, 2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 1, 2, 2, 5, 11],
 [5, 2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 1, 5, 2, 5, 11],
 [5, 2, 2, 5, 2, 2, 2, 5, 5, 5, 2, 2, 1, 5, 2, 5, 11],
 [5, 2, 2, 5, 2, 2, 2, 5, 5, 5, 2, 2, 1, 5, 5, 5, 11],
 [2, 2, 5, 2, 2, 5, 2, 5, 5, 2, 2, 5, 9, 5, 5, 2, 0],
 [2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 5, 9, 5, 2, 2, 0],
 [5, 2, 2, 5, 2, 2, 2, 5, 5, 5, 2, 2, 1, 2, 5, 2, 11],
 [5, 2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 1, 5, 2, 5, 11],
 [2, 5, 5, 2, 5, 2, 2, 2, 5, 5, 2, 2, 6, 5, 5, 2, 14],
 [2, 2, 5, 2, 2, 5, 5, 5, 5, 2, 2, 5, 9, 5, 2, 2, 0],
 [2, 2, 5, 2, 2, 2, 5, 2, 2, 2, 2, 2, 9, 2, 2, 2, 10],
 [2, 2, 5, 2, 2, 5, 5, 2, 2, 2, 2, 2, 1, 2, 2, 2, 10],
 [2, 2, 5, 2, 2, 5, 5, 2, 2, 2, 2, 2, 4, 2, 2, 2, 10],
 [2, 5, 5, 2, 5, 2, 5, 2, 5, 5, 2, 2, 6, 5, 2, 2, 14],
 [5, 2, 2, 5, 2, 2, 2, 5, 5, 5, 2, 2, 1, 5, 2, 5, 11],
 [2, 2, 5, 2, 

1-B
1)

In [74]:
from sklearn import preprocessing
import csv
with open("zoo.csv") as f:
    zoo = csv.reader(f)
    zoo = list(zoo)
zoo[0][0]='TRUE'
def uniq_values(list1):
    unique = []
    for i in list1:
        unique.extend(list(set(i)))
    unique=list(set(unique))
    le = preprocessing.LabelEncoder()
    le.fit(unique)
    print(le.classes_)
    return list(le.classes_)
unique = uniq_values(zoo)

['0' '2' '4' '5' '6' '8' 'FALSE' 'TRUE' 'amphibian' 'bird' 'fish' 'insect'
 'invertebrate' 'mammal' 'reptile']


In [75]:
zoo_list = []

le = preprocessing.LabelEncoder()
le.fit(unique)
for i in range(len(zoo)):
    zoo_list.append(list(le.transform(zoo[i])))
zoo_list

[[7, 6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 2, 6, 6, 7, 13],
 [7, 6, 6, 7, 6, 6, 6, 7, 7, 7, 6, 6, 2, 7, 6, 7, 13],
 [6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 7, 0, 7, 6, 6, 10],
 [7, 6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 2, 6, 6, 7, 13],
 [7, 6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 2, 7, 6, 7, 13],
 [7, 6, 6, 7, 6, 6, 6, 7, 7, 7, 6, 6, 2, 7, 6, 7, 13],
 [7, 6, 6, 7, 6, 6, 6, 7, 7, 7, 6, 6, 2, 7, 7, 7, 13],
 [6, 6, 7, 6, 6, 7, 6, 7, 7, 6, 6, 7, 0, 7, 7, 6, 10],
 [6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 7, 0, 7, 6, 6, 10],
 [7, 6, 6, 7, 6, 6, 6, 7, 7, 7, 6, 6, 2, 6, 7, 6, 13],
 [7, 6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 2, 7, 6, 7, 13],
 [6, 7, 7, 6, 7, 6, 6, 6, 7, 7, 6, 6, 1, 7, 7, 6, 9],
 [6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 7, 0, 7, 6, 6, 10],
 [6, 6, 7, 6, 6, 6, 7, 6, 6, 6, 6, 6, 0, 6, 6, 6, 12],
 [6, 6, 7, 6, 6, 7, 7, 6, 6, 6, 6, 6, 2, 6, 6, 6, 12],
 [6, 6, 7, 6, 6, 7, 7, 6, 6, 6, 6, 6, 4, 6, 6, 6, 12],
 [6, 7, 7, 6, 7, 6, 7, 6, 7, 7, 6, 6, 1, 7, 6, 6, 9],
 [7, 6, 6, 7, 6, 6, 6, 7, 7, 7, 6, 6, 2, 7, 6, 7, 13],
 [6, 6, 7, 6

2. Normalize

In [181]:
zoo_list_att = np.array(zoo_list)[:,:-1]
zoo_list_T = np.array(zoo_list_att).T
zoo_list_T[12]


array([2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 0, 0, 2, 4, 1, 2, 0, 0, 1, 1,
       2, 1, 4, 2, 2, 1, 2, 1, 4, 2, 1, 1, 0, 2, 2, 1, 0, 4, 4, 1, 4, 1,
       2, 2, 4, 2, 2, 2, 2, 4, 2, 5, 2, 2, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2,
       0, 2, 2, 2, 2, 1, 5, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 3, 0, 1,
       4, 2, 2, 2, 0, 1, 2, 1, 1, 4, 2, 0, 1], dtype=int64)

In [138]:
def min_max(list1):
    minimum = min(list1)
    maximum = max(list1)
    print(max(list1))
    return minimum,maximum
minimum,maximum = min_max(zoo_list_T[12])
maximum

5


5

In [182]:
array = []
for j in range(len(zoo_list_T[12])):
    print(abs(zoo_list_T[12][j] - minimum)/abs(maximum-minimum))
    array.append(abs(zoo_list_T[12][j] - minimum)/abs(maximum-minimum))
    
array

0.4
0.4
0.0
0.4
0.4
0.4
0.4
0.0
0.0
0.4
0.4
0.2
0.0
0.0
0.4
0.8
0.2
0.4
0.0
0.0
0.2
0.2
0.4
0.2
0.8
0.4
0.4
0.2
0.4
0.2
0.8
0.4
0.2
0.2
0.0
0.4
0.4
0.2
0.0
0.8
0.8
0.2
0.8
0.2
0.4
0.4
0.8
0.4
0.4
0.4
0.4
0.8
0.4
1.0
0.4
0.4
0.2
0.2
0.2
0.2
0.0
0.0
0.0
0.4
0.4
0.4
0.0
0.4
0.4
0.4
0.4
0.2
1.0
0.0
0.0
0.2
0.0
0.0
0.2
0.2
0.0
0.0
0.0
0.2
0.2
0.6
0.0
0.2
0.8
0.4
0.4
0.4
0.0
0.2
0.4
0.2
0.2
0.8
0.4
0.0
0.2


[0.4,
 0.4,
 0.0,
 0.4,
 0.4,
 0.4,
 0.4,
 0.0,
 0.0,
 0.4,
 0.4,
 0.2,
 0.0,
 0.0,
 0.4,
 0.8,
 0.2,
 0.4,
 0.0,
 0.0,
 0.2,
 0.2,
 0.4,
 0.2,
 0.8,
 0.4,
 0.4,
 0.2,
 0.4,
 0.2,
 0.8,
 0.4,
 0.2,
 0.2,
 0.0,
 0.4,
 0.4,
 0.2,
 0.0,
 0.8,
 0.8,
 0.2,
 0.8,
 0.2,
 0.4,
 0.4,
 0.8,
 0.4,
 0.4,
 0.4,
 0.4,
 0.8,
 0.4,
 1.0,
 0.4,
 0.4,
 0.2,
 0.2,
 0.2,
 0.2,
 0.0,
 0.0,
 0.0,
 0.4,
 0.4,
 0.4,
 0.0,
 0.4,
 0.4,
 0.4,
 0.4,
 0.2,
 1.0,
 0.0,
 0.0,
 0.2,
 0.0,
 0.0,
 0.2,
 0.2,
 0.0,
 0.0,
 0.0,
 0.2,
 0.2,
 0.6,
 0.0,
 0.2,
 0.8,
 0.4,
 0.4,
 0.4,
 0.0,
 0.2,
 0.4,
 0.2,
 0.2,
 0.8,
 0.4,
 0.0,
 0.2]

In [184]:
import numpy as np
zoo_list_att = np.array(zoo_list)[:,:-1]
def min_max(list1):
    minimum = min(list1)
    maximum = max(list1)
    return minimum,maximum
zoo_list_T = np.array(zoo_list_att).T
zoo_ = []
for i in range(len(zoo_list_T)):
    minimum,maximum = min_max(zoo_list_T[i])
    array = []
    for j in range(len(zoo_list_T[0])):
        array.append(abs(zoo_list_T[i][j] - minimum)/abs(maximum-minimum))
    zoo_.append(array)
zoo_ = np.array(zoo_)
zoo_att = zoo_.T

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]


In [185]:
for i in zoo_att:
    print(i)

[1.  0.  0.  1.  0.  0.  1.  1.  1.  1.  0.  0.  0.4 0.  0.  1. ]
[1.  0.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.4 1.  0.  1. ]
[0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
[1.  0.  0.  1.  0.  0.  1.  1.  1.  1.  0.  0.  0.4 0.  0.  1. ]
[1.  0.  0.  1.  0.  0.  1.  1.  1.  1.  0.  0.  0.4 1.  0.  1. ]
[1.  0.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.4 1.  0.  1. ]
[1.  0.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.4 1.  1.  1. ]
[0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.]
[0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
[1.  0.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.4 0.  1.  0. ]
[1.  0.  0.  1.  0.  0.  1.  1.  1.  1.  0.  0.  0.4 1.  0.  1. ]
[0.  1.  1.  0.  1.  0.  0.  0.  1.  1.  0.  0.  0.2 1.  1.  0. ]
[0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.  0.  1.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.4 0.  0.  0. ]
[0.  0.  1.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.8 0.  0.  0. ]
[0.  1.  1.  0.  1.  0. 

In [125]:
for i in zoo_list_att:
    print(i)

[1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1]
[1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1]
[0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0]
[1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1]
[1 0 0 1 0 0 1 1 1 1 0 0 0 1 0 1]
[1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1]
[1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 1]
[0 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0]
[0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0]
[1 0 0 1 0 0 0 1 1 1 0 0 0 0 1 0]
[1 0 0 1 0 0 1 1 1 1 0 0 0 1 0 1]
[0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0]
[0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0]
[0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0]
[0 1 1 0 1 0 1 0 1 1 0 0 0 1 0 0]
[1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1]
[0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1]
[0 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1]
[0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0]
[0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0]
[1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1]
[0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1]
[0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0]
[0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 0]
[1 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0]
[1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1]
[1 0 0 1 0 0 1